// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -package=mocks -source=service.go -destination=mocks/service.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// GetAllBy mocks base method.
func (m *MockUserRepository) GetAllBy() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllBy")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllBy indicates an expected call of GetAllBy.
func (mr *MockUserRepositoryMockRecorder) GetAllBy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllBy", reflect.TypeOf((*MockUserRepository)(nil).GetAllBy))
}

// MockAutoRepository is a mock of AutoRepository interface.
type MockAutoRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAutoRepositoryMockRecorder
	isgomock struct{}
}

// MockAutoRepositoryMockRecorder is the mock recorder for MockAutoRepository.
type MockAutoRepositoryMockRecorder struct {
	mock *MockAutoRepository
}

// NewMockAutoRepository creates a new mock instance.
func NewMockAutoRepository(ctrl *gomock.Controller) *MockAutoRepository {
	mock := &MockAutoRepository{ctrl: ctrl}
	mock.recorder = &MockAutoRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAutoRepository) EXPECT() *MockAutoRepositoryMockRecorder {
	return m.recorder
}

// Search mocks base method.
func (m *MockAutoRepository) Search(string2 string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", string2)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockAutoRepositoryMockRecorder) Search(string2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockAutoRepository)(nil).Search), string2)
}
